### ISSUE TITLE
"schema browser" "key" column is empty

### ISSUE THREAD

**Issue by NovemLinguae** [MusikAnimal/sql-optimizer#18]
When the "Schema browser" button is pressed, then you click on a table, all the "Key" columns that I spot checked are empty. I was expecting Primary Key columns to be marked somehow.

![2021-04-02_040414](https://user-images.githubusercontent.com/79697282/113410851-3847a280-9369-11eb-8564-a22b2f4638ef.png)

**Comment by MusikAnimal** [comment]
This is just the output of running `DESCRIBE` on the table. I can't explain why the primary keys aren't showing, but unfortunately there's nothing I can do about it :( The issue will need to be raised with the Cloud Services team, who maintains the replica databases. You can submit a task to them on [Phabricator](https://phabricator.wikimedia.org/maniphest/task/edit/form/1/?projects=data-services).
