### ISSUE TITLE
"schema browser" requests returns 500

### ISSUE THREAD

**Issue by kosovojs** [MusikAnimal/sql-optimizer#23]
e.g., https://sql-optimizer.toolforge.org/describe/enwiki_p

**Comment by MusikAnimal** [comment]
Forgot to fix this following the update to the [new replicas design](https://wikitech.wikimedia.org/wiki/News/Wiki_Replicas_2020_Redesign). Fixed with https://github.com/MusikAnimal/sql-optimizer/commit/ba6a3cede2f77759c8eea1267e06edffdacf8de1. Thanks for reporting!
