### ISSUE TITLE
Toolforge SQL Optimizer broken (unknown thread ID error)

### ISSUE THREAD

**Issue by lucaswerkmeister** [MusikAnimal/sql-optimizer#3]
Trying to use the SQL Optimizer with any query ([example](https://tools.wmflabs.org/sql-optimizer?use=enwiki_p&sql=SELECT+page_namespace%2C+page_is_new%2C+COUNT%28*%29%0D%0AFROM+revision%0D%0AJOIN+actor+ON+actor_id+%3D+rev_actor%0D%0AJOIN+page+ON+rev_page+%3D+page_id+AND+page_namespace+IN+%280%2C1%29+AND+page_is_redirect+%3D+1%0D%0AJOIN+centralauth_p.globaluser+ON+gu_name+%3D+actor_name%0D%0AWHERE+gu_home_db+%3D+%27enwiki%27+AND+rev_len+%3E+%272000%27+AND+actor_name+LIKE+%27Ada%25%27%0D%0AGROUP+BY+page_namespace%2C+page_is_new)) results in the following error:

> SHOW EXPLAIN failed: Unknown thread id: 6358001

(The thread ID is different every time.)

**Comment by MusikAnimal** [comment]
We're back online! Thank you for letting me know

**Comment by joeroe** [comment]
This is happening again for me:

> SHOW EXPLAIN failed: Unknown thread id: 658389835 This may be a connection issue. If you believe your query is valid, try resubmitting.

[Query](https://sql-optimizer.toolforge.org/?use=enwiki_p&sql=SELECT%0D%0A++actor.actor_id%2C%0D%0A++actor.actor_name%2C%0D%0A++user.user_id%2C%0D%0A++user.user_name%2C%0D%0A++user.user_real_name%2C%0D%0A++user.user_touched%2C%0D%0A++user.user_editcount%0D%0AFROM%0D%0A++actor%0D%0A++LEFT+JOIN+user+ON+user.user_id+%3D+actor.actor_user%0D%0AWHERE%0D%0A++actor.actor_id+IN+%28%0D%0A++++SELECT%0D%0A++++++DISTINCT+rev_actor%0D%0A++++FROM%0D%0A++++++revision%0D%0A++++WHERE%0D%0A++++++rev_page+IN+%28%0D%0A++++++++SELECT%0D%0A++++++++++page.page_id%0D%0A++++++++FROM%0D%0A++++++++++page_assessments+AS+ass%0D%0A++++++++++INNER+JOIN+page+ON+page.page_id+%3D+ass.pa_page_id%0D%0A++++++++WHERE%0D%0A++++++++++ass.pa_project_id+%3D+406%0D%0A++++++++++AND+page.page_namespace+%3D+0%0D%0A++++++++++AND+page.page_is_redirect+%3D+0%0D%0A++++++%29%0D%0A++%29)

**Comment by MusikAnimal** [comment]
Fixed again! Sorry for the inconvenience. From this point forward, I think we're a bit more future-proof.
